c_compiler:
- gcc
c_compiler_version:
- '12'
cairo:
- '1'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
glib:
- '2'
libffi:
- '3.4'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.11.* *_cpython
- 3.10.* *_cpython
- 3.9.* *_cpython
- 3.8.* *_cpython
target_platform:
- linux-armv7l
